---
title: "lab-exercise-3-1"
output: md_document
---

## Exploring the Cocoli Dataset

```{r}
cocoli_dat <- read.table("~/Desktop/eeb-177/class-assignments/classwork-21-Feb/cocoli.txt", header = T)
head(cocoli_dat)
str(cocoli_dat)
View(cocoli_dat)
sizes_94 <- cocoli_dat$dbh1
names(sizes_94) <- cocoli_dat$tag
sizes_94[1:5]

trees_171_94 <- which(sizes_94 == 171)

sizes_97 <- cocoli_dat$dbh2
names(sizes_97) <- cocoli_dat$tag

sizes_98 <- cocoli_dat$dbh3
names(sizes_98) <- cocoli_dat$tag

sizes_97[trees_171_94]

#relative growth rate (RGR) 1997-1994
yrly_RGR_1 <- ((cocoli_dat$dbh2 - cocoli_dat$dbh1)/cocoli_dat$dbh1)/3
cocoli_dat$rgr1 <- yrly_RGR_1
View(cocoli_dat)
```

## Plots

```{r}
# make histograms with hist()
# barplots with barplot()
# boxplots with boxplot
# scatter plot with plot()

hist(cocoli_dat$dbh1, xlab = "DBH in 1994 (mm)", main = "Distributions of sizes in 1994", col = "red", xlim = c(0, 2000))
```


```{r}
library(ggplot2)

ggplot(cocoli_dat) + geom_histogram(aes(dbh1)) + 
  geom_histogram(aes(dbh2), fill = "red", alpha = 0.2) +
  ggtitle("Distribution of sizes in 1994")
  
```

# ggplot Tutorial 
###### From http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html#org93999d8

```{r}
housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])
hist(housing$Home.Value)
ggplot(housing, aes(x = Home.Value)) +
  geom_histogram()
####
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "red"),
       pch=c(1, 1))
####
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()
####
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point()

ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point()


####
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))
####
p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth() # this function calls upon method 'loess'

####
p1 + 
  geom_text(aes(label=State), size = 3)
####
install.packages("ggrepel") 
library("ggrepel")
p1 + 
  geom_point() + 
  geom_text_repel(aes(label=State), size = 3)
####
p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red
####
p1 +
  geom_point(aes(color=Home.Value, shape = region))

```

## Exercise I

```{r}
dat <- read.csv("Rgraphics/dataSets/EconomistData.csv")
head(dat)

#    Create a scatter plot with CPI on the x axis and HDI on the y axis.
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point()
#    Color the points blue.
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(col = "blue")
#    Map the color of the the points to Region.
ggplot(dat, aes(x = CPI, y = HDI, col = Region)) + geom_point()
#    Make the points bigger by setting size to 2
ggplot(dat, aes(x = CPI, y = HDI, col = Region)) + geom_point(size = 2)
#    Map the size of the points to HDI.Rank
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank, col = Region)) + geom_point()

```

```{r}
args(geom_histogram)
args(stat_bin)

p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()

p2 + geom_histogram(stat = "bin", binwidth=4000)

####
housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))

ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
  geom_bar(stat="identity")

```

## Exercise II

```{r}
# Re-create a scatter plot with CPI on the x axis and HDI on the y axis (as you did in the previous exercise).
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point()
# Overlay a smoothing line on top of the scatter plot using geom_smooth.
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() +
  geom_smooth()
# Overlay a smoothing line on top of the scatter plot using geom_smooth, but use a linear model for the predictions. Hint: see ?stat_smooth.
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() +
  geom_smooth(method = "lm")
# Overlay a smoothing line on top of the scatter plot using geom_line. Hint: change the statistical transformation.
smooth_line = loess(HDI ~ CPI, dat)
loessFit <- data.frame(x=smooth_line$x, y=smooth_line$fitted)
loessFit <- loessFit[order(smooth_line$x),]
colnames(loessFit)[2] <- "HDI"
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() +
  geom_line(data = loessFit, stat = "identity")

```

```{r}
p3 <- ggplot(housing,
             aes(x = State,
                 y = Home.Price.Index)) + 
        theme(legend.position="top",
              axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)))

p4 + scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"))

p4 +
  scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")
library(scales) 
p4 +
  scale_color_gradient2(name="",
                        breaks = c(1976, 1994, 2013),
                        labels = c("'76", "'94", "'13"),
                        low = muted("blue"),
                        high = muted("red"),
                        mid = "gray60",
                        midpoint = 1994)


```


## Exercise III

```{r}
# Create a scatter plot with CPI on the x axis and HDI on the y axis. Color the points to indicate region.
ggplot(dat, aes(x = CPI, y = HDI, col = Region)) + geom_point()
# Modify the x, y, and color scales so that they have more easily-understood names (e.g., spell out "Human development Index" instead of "HDI").
ggplot(dat, aes(x = CPI, y = HDI, col = Region)) + geom_point() +
  scale_x_continuous(name = "Corruption Perception Index") +
  scale_y_continuous(name = "Human development Index")
# Modify the color scale to use specific values of your choosing. Hint: see ?scale_color_manual.
ggplot(dat, aes(x = CPI, y = HDI, col = Region)) + geom_point() +
  scale_x_continuous(name = "Corruption Perception Index") +
  scale_y_continuous(name = "Human development Index") +
  scale_colour_manual(values = c("red", "blue", "green", "purple", "orange", "black"))
```

```{r}
p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))

(p5 <- p5 + geom_line() +
   facet_wrap(~State, ncol = 10))
p5 + theme_linedraw()

p5 + theme_minimal() +
  theme(text = element_text(color = "turquoise"))
```



```{r}
# to make markdown file with outputs
# rmarkdown::render("file_name.Rmd", output_format = "md_document")
# Or just change the output to md_document
```
